export const dataSiswa = [
  {
    name: "MUHAMMAD REZA H.",
    school: "BINUS INTERNATIONAL SCHOOL SERPONG",
    major: "AKUNTANSI - UGM",
  },
  {
    name: "MUHAMMAD DINDA K. A.",
    school: "S1 KEDOKTERAN TRISAKSI",
    major: "S2 SPESIALIS ILMU BEDAH - UI",
  },
  {
    name: "PUTI K. D.",
    school: "SMA LABSCHOOL JAKARTA",
    major: "TEKNIK METALURGI DAN MATERIAL - UI",
  },
  { name: "NABILA A. D. P.", school: "SMAN 70 JAKARTA", major: "KIMIA - UI" },
  {
    name: "R. RAFFY P.",
    school: "SMA LABSCHOOL JAKARTA TIMUR",
    major: "BIOLOGI - UI",
  },
  {
    name: "DJAKWAN V. M.",
    school: "SMAIT ALMAKA",
    major: "ILMU KEOLAHRAGAAN - UPI",
  },
  { name: "BIMA M. W.", school: "SMA N 2 TANGSEL", major: "AKUNTANSI - UGM" },
  { name: "WILDA A.", school: "SMAN 3 BOGOR", major: "AKTUARIA - IPB" },
  {
    name: "M. ZHAFRAN N. S.",
    school: "SMAN 1 MEDAN",
    major: "HUKUM - UDAYANA",
  },
  {
    name: "ATHALA T. I.",
    school: "SMA NEGERI 3 BANDA ACEH",
    major: "ARSITEKTUR - UI",
  },
  {
    name: "AMANDA A.",
    school: "SMAN 28 JAKARTA",
    major: "MANAJEMEN INTER - UI",
  },
  {
    name: "REYNALDO R. P. W.",
    school: "SMAN 39 JAKARTA",
    major: "ILMU HUKUM - UI",
  },
  {
    name: "ZAID HABIB P. A. D.",
    school: "SMAN 2 TANGERANG SELATAN",
    major: "TEKNIK METALURGI DAN MATERIAL INTER - UI",
  },
  {
    name: "INDAH W.",
    school: "SMA NEGERI 3 BATAM",
    major: "AKIDAH DAN FILSAFAT ISLAM - UIN JAKARTA",
  },
  {
    name: "SAFANNY P.",
    school: "SMA GLOBAL ISLAMIC SCHOOL 2 SERPONG",
    major: "ARSITEKTUR - UPI",
  },
  {
    name: "MUTIARA NUR R.",
    school: "SMA TARUNA NUSANTARA",
    major: "MANAJEMEN INTER - UI",
  },
  {
    name: "ANGGI A. H.",
    school: "BINUS SCHOOL SERPONG",
    major: "PSIKOLOGI INTER - UI",
  },
  {
    name: "NADHILAH A.",
    school: "SMAN 8 PEKANBARU",
    major: "PSIKOLOGI INTER - UNAIR",
  },
  {
    name: "M. S. NURAGUNG",
    school: "SMAN 58 JAKARTA",
    major: "MANAJEMEN - UPN VETERAN JAKARTA",
  },
  {
    name: "ATHAYA W.",
    school: "SMAN 75 JAKARTA",
    major: "TEKNOLOGI PANGAN - ITERA",
  },
  {
    name: "M. RIZQI",
    school: "SMA NEGERI 78 JAKARTA",
    major: "TEKNIK MESIN - UNJ",
  },
  {
    name: "HANA L.",
    school: "SMA TARUNA NUSANTARA",
    major: "TEKNIK INDUSTRI - UI",
  },
  {
    name: "SAFANNY P.",
    school: "SMA GLOBAL ISLAMIC SCHOOL 2 SERPONG",
    major: "TEKNOLOGI PANGAN - UNTIRTA",
  },
  {
    name: "NADHILAH A.",
    school: "SMAN 8 PEKANBARU",
    major: "PSIKOLOGI - UI",
  },
  {
    name: "MIFTA A. A. S.",
    school: "SMAN 2 MANOKWARI",
    major: "FISIOTERAPI - UI (VOKASI)",
  },
  {
    name: "ALYA F.",
    school: "SMA NEGERI 8 JAKARTA",
    major: "PENDIDIKAN DOKTER - UI",
  },
  {
    name: "FELISHA S.",
    school: "SMA AL-AZHAR 3 PUSAT",
    major: "SASTRA PERANCIS - UI",
  },
  {
    name: "M. ADITYA K.",
    school: "SMAN 68 JAKARTA",
    major: "TEKNIK KOMPUTER - UI",
  },
  { name: "M. RIZQI", school: "SMA NEGERI 78 JAKARTA", major: "KIMIA - UGM" },
  {
    name: "AMELIA M. N.",
    school: "MAN INSAN CENDEKIA SERPONG",
    major: "SISTEM INFORMASI - UI",
  },
  {
    name: "INDAH W.",
    school: "SMA NEGERI 3 BATAM",
    major: "SASTRA INDONESIA - UNDIP",
  },
  {
    name: "SARAH RAHMA A. K.",
    school: "SMA GARUDA CENDEKIA",
    major: "HUKUM - UNDIP",
  },
  { name: "PUTI S. N.", school: "AL AZHAR PUSAT", major: "MANAJEMEN - UB" },
  {
    name: "ARDI ILMAN M.",
    school: "AL AZHAR 19 JAKTIM",
    major: "MATEMATIKA - UNPAD",
  },
  {
    name: "SYIFA A. A.",
    school: "SMAN 8 JAKARTA",
    major: "SISTEM INFORMASI - UB",
  },
  {
    name: "SAFANNY P.",
    school: "SMA GLOBAL ISLAMIC SCHOOL 2 SERPONG",
    major: "KESEHATAN MASYARAKAT - UPN VETERAN JAKARTA",
  },
  {
    name: "MOZA R. I.",
    school: "SMAN 5 BALIKPAPAN",
    major: "ILMU KEPERAWATN - UNPAD",
  },
  {
    name: "SHINTA S. P. H.",
    school: "SMAN 13 JAKARTA",
    major: "TEKNIK PERTANIAN - UNPAD",
  },
  {
    name: "MUTIARA PUTRI A.",
    school: "SMAN 26 JAKARTA",
    major: "ILMU HUKUM - UNPAD",
  },
  {
    name: "M. ADITYA K.",
    school: "SMAN 68 JAKARTA",
    major: "TEKNIK INFORMATIKA - UNPAD",
  },
  {
    name: "M. AULIA",
    school: "SMAN 7 TANGERANG SELATAN",
    major: "FARMASI - UNAIR",
  },
  {
    name: "BERKAH RIZKI F. F.",
    school: "SMAN 56 JAKARTA",
    major: "AKUNTANSI SEKTOR PUBLIK - UNPAD",
  },
  {
    name: "SYIFA A. A.",
    school: "SMAN 8 JAKARTA",
    major: "TEKNOLOGI SAINS DATA - UNAIR",
  },
  {
    name: "MOZA R. I.",
    school: "SMAN 5 BALIKPAPAN",
    major: "BUDIDAYA TERNAK - UNSOED",
  },
  {
    name: "ALIF RIZKY R.",
    school: "SMAN 80 JAKARTA",
    major: "TEKNIK PERKAPALAN - UPN VETERAN JAKARTA",
  },
  {
    name: "SUCI SEPTYANI S. P.",
    school: "SMAN 2 SAWAHLUNTO",
    major: "TELEKOMUNIKASI - PNJ",
  },
  {
    name: "BERKAH RIZKI F. F.",
    school: "SMAN 56 JAKARTA",
    major: "TEKNOLOGI REKAYASA OTOMASI - UNDIP",
  },
  {
    name: "ALVINA P.",
    school: "PENABUR 2 JAKARTA",
    major: "ILMU KEPERAWATAN",
  },
  { name: "KEVIN H.", school: "SMAN 4 JAKARTA", major: "ILMU KOMPUTER - UI" },
  {
    name: "SYIFA A.A.",
    school: "SMAN 8 JAKARTA",
    major: "SISTEM INFORMASI - ITS",
  },
  { name: "FACHRI R. R. P.", school: "SMA DWIWARNA", major: "HUKUM - UNDIP" },
  {
    name: "RAHMADITA S. P. A.",
    school: "SMAN 5 PARE PARE",
    major: "PENDIDIKAN DOKTER GIGI - UNHAS",
  },
  {
    name: "SYIFA A. A.",
    school: "SMAN 8 JAKARTA",
    major: "DATA SAINS - UPN VETERAN JAWA TIMUR",
  },
  {
    name: "CHARISSE N.",
    school: "SMAK 1 PENABUR",
    major: "PSIKOLOGI INTER - UI",
  },
  {
    name: "SASQIA S. A.",
    school: "SMA LABSCHOOL JAKARTA",
    major: "ILMU HUKUM - UB",
  },
  {
    name: "KAYLA M.I H.",
    school: "SMA GARUDA CENDEKIA",
    major: "SEKOLAH BISNIS DAN MANAJEMEN INTER - ITB",
  },
  {
    name: "AULIA MEDINAH M.",
    school: "SMA DIPONEGORO 1 JAKARTA",
    major: "KEDOKTERAN- UIN",
  },
  { name: "JEANICE K.", school: "SMAK 1 PENABUR", major: "BIOLOGI - UI" },
  {
    name: "MOZA R. I.",
    school: "SMAN 5 BALIKPAPAN",
    major: "TEKNIK LINGKUNGAN - UNAIR",
  },
  {
    name: "SAFANNY P.",
    school: "SMA GLOBAL ISLAMIC SCHOOL 2 SERPONG",
    major: "AGROEKOTEKNOLOGI - UB",
  },
  { name: "NABILA H.I.", school: "SMAN 109 JAKARTA", major: "HUKUM - UNDIP" },
  {
    name: "MERDIANSYAH M. M.",
    school: "SMA TERPADU KRIDA NUSANTARA",
    major: "PENDIDIKAN AKUNTANSI - UNS",
  },
  {
    name: "PUTI S. N.",
    school: "SMA ISLAM AL AZHAR 1",
    major: "SEKOLAH BISNIS DAN MANAJEMEN - ITB",
  },
  {
    name: "SYARIFAH D. R.",
    school: "SMAN 2 PALANGKARAYA",
    major: "SISTEM INFORMASI - ITS",
  },
  {
    name: "EDRO M. A. S.",
    school: "SMAK PENABUR KELAPA GADING",
    major: "TEKNIK ELEKTRO INTER- UI",
  },
  {
    name: "M. S. NURAGUNG",
    school: "SMAN 58 JAKARTA",
    major: "AKUNTANSI - UNDIP",
  },
  {
    name: "ZAHRA R. M.",
    school: "SMAN 21 JAKARTA",
    major: "ARSITEKTUR INTER - UI",
  },
  { name: "JEANICE K.", school: "SMAK 1 PENABUR", major: "GIZI - UB" },
  { name: "DWINTA P.", school: "SMAN 3 JAKARTA", major: "HUKUM INTER - UGM" },
  {
    name: "JUVEN",
    school: "SMAN 4 TANGERANG SELATAN",
    major: "TEKNIK FISIKA - ITERA",
  },
  {
    name: "CATHLIN L. M. M.",
    school: "SMAN 70 JAKARTA",
    major: "PSIKOLOGI - UI",
  },
  { name: "FIRDA R. B.", school: "SMAN 68 JAKARTA", major: "FTMD - ITB" },
  {
    name: "SATINE Z.",
    school: "SMA DIAN DIDAKTIKA",
    major: "PSIKOLOGI INTER - UI",
  },
  {
    name: "RACHMADINSA D.",
    school: "SMAN 21 PULOMAS",
    major: "HUKUM INTER - UGM",
  },
  { name: "DANTI", school: "SMUN 37 JAKARTA", major: "KIMIA - UNUD" },
  {
    name: "EVARIANTI",
    school: "SMAS MALAHAYATI",
    major: "MANAJEMEN - UPN VETERAN JAWA TIMUR",
  },
  {
    name: "RIFQY A.",
    school: "SMAN 11 JAKARTA",
    major: "ILMU KOMPUTER - UNILA",
  },
  {
    name: "SALSABILLA P. P.",
    school: "SMAN 1 DEPOK",
    major: "TEKNIK INDUSTRI INTER - UI",
  },
  { name: "ARIK R.", school: "SMA N 81 JAKARTA", major: "STEI - ITB" },
  { name: "TABINA P.", school: "SMAN 28 JAKSEL", major: "KEDOKTERAN - UGM" },
  {
    name: "ALTHOF R. G. P.",
    school: "AL-AZHAR 3 JAKSEL",
    major: "MANAJEMEN - UNDIP",
  },
  {
    name: "N. KHARISMA",
    school: "SMA DWIWARNA INTER. BOARDING SCHOOL",
    major: "ILMU HUKUM - UI",
  },
  {
    name: "REYNA A.",
    school: "SMAN 55 JAKARTA",
    major: "TEKNOLOGI PANGAN - IPB",
  },
  {
    name: "M. DZELDY R.",
    school: "SMK N 4 BOGOR",
    major: "STPN (SEKOLAH TINGGI PERTANAHAN NASIONAL)",
  },
  {
    name: "RADYA N. PR. H.",
    school: "SMAIT NURURRAHMAN",
    major: "TEKNIK PERKAPALAN - ITS",
  },
  {
    name: "R. RAIHAN",
    school: "SMAN 1 CIBINONG",
    major: "TEKNIK MESIN - UI",
  },
  {
    name: "ALTHOF R. G. P.",
    school: "AL-AZHAR 3 JAKSEL",
    major: "HUKUM INTER - UGM",
  },
  {
    name: "HUMAM P. D.",
    school: "SMAN 54 JAKARTA",
    major: "TEKNIK MESIN INTER - ITB",
  },
  {
    name: "M. ANDHIKA A. H.",
    school: "SMA TARUNA NUSANTARA",
    major: "MANAJEMEN INTER - UI",
  },
  {
    name: "M. DHIA A.",
    school: "SMAN 91 JAKARTA",
    major: "TEKNIK MESIN INTER - UI",
  },
  {
    name: "GREGORIUS A. S.",
    school: "SMA LABSCHOOL JAKARTA",
    major: "ILMU KOMUNIKASI INTER - UI",
  },
  {
    name: "SANNY M.",
    school: "SMAT KRIDA NUSANTARA BANDUNG",
    major: "HUKUM - UDAYANA",
  },
  {
    name: "KHAZZA K. A.",
    school: "SMA 67 JAKARTA",
    major: "HUKUM - UPN VETERAN JAKARTA",
  },
  {
    name: "ANGGI F.",
    school: "SMAN 1 BUKITTINGGI",
    major: "ADMINISTRASI - UPI",
  },
  { name: "JOANNA M.", school: "SMA SANTA URSULA", major: "STEI - ITB" },
  {
    name: "ALTHOF R. G. P.",
    school: "AL-AZHAR 3 JAKSEL",
    major: "MANAJEMEN - UNS",
  },
  {
    name: "FATIHA N. K.",
    school: "INDOOROOPILLY STATE HIGH SCHOOL, AUSTRALIA",
    major: "SASTRA INGGRIS - UI",
  },
  {
    name: "RADYA N. P. H.",
    school: "SMAIT NURURRAHMAN",
    major: "PETERNAKAN - UB",
  },
  {
    name: "ZAHRA Q. A.",
    school: "MA PEMBANGUNAN UIN",
    major: "KEDOKTERAN - UIN JAKARTA",
  },
  {
    name: "DEFANNA D. V.",
    school: "SEKOLAH MADANIA BOGOR",
    major: "HUKUM INTER - UI",
  },
  {
    name: "MARSYA M.",
    school: "SMAN 3 JAKARTA",
    major: "ILMU KOMUNIKASI - UNDIP",
  },
  {
    name: "HUMAM P. D.",
    school: "SMAN 54 JAKARTA",
    major: "TEKNIK MESIN - UI",
  },
  {
    name: "WAHYU AJI B.",
    school: "SMAN 21 JAKARTA",
    major: "TEKNIK MESIN - UB",
  },
  {
    name: "FABYAN N. A.",
    school: "SMAN 29",
    major: "MANAJEMEN - INTER UNAIR",
  },
  {
    name: "ALIFIA T. D.",
    school: "SMAN 42 JAKARTA",
    major: "ARSITEKTUR INTERIOR - UI",
  },
  { name: "NAFISA K. M.", school: "SMAN 55 JAKARTA", major: "BIOLOGI - UI" },
  {
    name: "KAYLEE R. D.",
    school: "SMAN 70 JAKARTA",
    major: "ILMU KOMPUTER - UI",
  },
  {
    name: "LITA Y. W.",
    school: "SMA SEKOLAH GLOBAL MANDIRI",
    major: "AKTUARIA - IPB",
  },
  {
    name: "GHIVANDHA Z. Z.",
    school: "SMA LABSCHOOL JAKARTA",
    major: "TEKNIK SIPIL - UNS",
  },
  {
    name: "M. KUDRAT T.",
    school: "SMA PLUS N 17 PALEMBANG",
    major: "MANAJEMEN - INTER UNDIP",
  },
  {
    name: "CHAU Y. A.",
    school: "JAKARTA TAIPEI SCHOOL",
    major: "ILMU DAN INDUSTRI PETERNAKAN - INTER UGM",
  },
  {
    name: "RATU HAURA S.",
    school: "JAKARTA ISLAMIC SCHOOL",
    major: "SASTRA PERANCIS - UNPAD",
  },
  {
    name: "TIARA A.",
    school: "SMAN 84 JAKARTA",
    major: "KEDOKTERAN - UNSRI",
  },
  {
    name: "ALIYA S. L.",
    school: "SMA AL-WILDAN ISLAMIC SCHOOL",
    major: "GIZI - UPN VETERAN JAKARTA",
  },
  {
    name: "ADINDA PUTRI N.",
    school: "SMA LABSCHOOL JAKARTA",
    major: "PSIKOLOGI - UNS",
  },
  {
    name: "CHAU Y. A.",
    school: "JAKARTA TAIPEI SCHOOL",
    major: "KEDOKTERAN HEWAN - INTER UNAIR",
  },
  {
    name: "ENRICO GERALD T.",
    school: "SMAN 1 TOMOHON",
    major: "MANAJEMEN - UNSRAT",
  },
  {
    name: "M. FAISHAL A.",
    school: "SMAN 9 TANGSEL",
    major: "SISTEM INFORMASI - NUPN VETERAN JAKARTA",
  },
  { name: "ANASTASYA K. F.", school: "SMAN 28", major: "KEDOKTERAN - UNPAD" },
  {
    name: "GHIVANDHA Z. Z.",
    school: "SMA LABSCHOOL JAKARTA",
    major: "TEKNIK INDUSTRI - UNS",
  },
  {
    name: "KAYLA N. S.",
    school: "SMA IC AL-KAUSAR",
    major: "TEKNIK SIPIL - UNMAL",
  },
  {
    name: "DANIEL VALENTINO M.",
    school: "SMAN 5 DENPASAR",
    major: "HUKUM - UGM",
  },
  {
    name: "NICHOLAS PRATAMA B. E.",
    school: "SMA MARSUDIRINI BEKASI",
    major: "HUKUM - UPN VETERAN JAKARTA",
  },
  {
    name: "M. AJI P.",
    school: "SMA KHARISMA BANGSA",
    major: "ILMU DAN INDUSTRI PETERNAKAN - UGM",
  },
  { name: "DEVINA J.", school: "SMAN 1 BEKASI", major: "FTTM - ITB" },
  {
    name: "AMODYA D. N.",
    school: "SMAN 55 JAKARTA",
    major: "KEDOKTERAN HEWAN - UNPAD",
  },
  {
    name: "KURNIAWAN G.",
    school: "SMAN 1 KOTAMOBAGU",
    major: "ILMU HUKUM - UNSRAT",
  },
  {
    name: "M. RAMADHAN EZRA G. S.",
    school: "SMA AL AZHAR 19 CIRACAS",
    major: "TEKNIK SIPIL - INTER UNDIP",
  },
  {
    name: "LIVIA Z. K.",
    school: "SMAN 28 JAKARTA",
    major: "TEKNIK BIOMEDIS - UI",
  },
  {
    name: "GHIVANDHA Z. Z.",
    school: "SMA LABSCHOOL JAKARTA",
    major: "FTSL - ITB",
  },
  {
    name: "M. HANIF M.",
    school: "SMA AL IZHAR",
    major: "TEKNIK KIMIA - INTER ITS",
  },
  {
    name: "NABIL MAULIDI I.",
    school: "SMAN 2 BANDUNG",
    major: "TEKNIK PERTANIAN - UNPAD",
  },
  {
    name: "SYIFA AINUN F. S.",
    school: "SMA DAARUT TAUHID BANDUNG",
    major: "KEDOKTERAN GIGI - UNPAD",
  },
  {
    name: "MARTINA C. P.",
    school: "SMA KESATUAN BANGSA YOGYAKARTA",
    major: "SISTEM INFORMASI - UB",
  },
  {
    name: "M. KUDRAT T.",
    school: "SMA PLUS N 17 PALEMBANG",
    major: "MANAJEMEN - INTER ITB",
  },
  {
    name: "CHRISTIAN N. M.",
    school: "SMAN 96 JAKARTA",
    major: "MANAJEMEN - UI",
  },
  {
    name: "M. Raihan",
    school: "SMAN 14 JAKARTA",
    major: "TEKNIK ELEKTRO - ITS",
  },
  {
    name: "TSABITUL A.",
    school: "SMAIT AL QUDWAH",
    major: "SEJ. PERADABAN ISLAM - UIN BANDUNG",
  },
  {
    name: "GHIVANDHA Z. Z.",
    school: "SMA LABSCHOOL JAKARTA",
    major: "TEKNIK SIPIL - UB",
  },
  {
    name: "RATU HAURA S.",
    school: "JAKARTA ISLAMIC SCHOOL",
    major: "ILMU KOMUNIKASI - UI INTER",
  },
  {
    name: "M.SYAUGI. K.",
    school: "SMAN 2 TANGERANG SELATAN",
    major: "PENDIDIKAN DOKTER - UI",
  },
  { name: "NISRINA A.", school: "SMA DWIWARNA", major: "FARMASI - UI" },
  {
    name: "ASHLEY A. A.",
    school: "CITA BUANA",
    major: "TEKNIK INDUSTRI - UI INTER",
  },
  {
    name: "MARTINA CAHYA P.",
    school: "SMA KESATUAN BANGSA YOGYAKARTA",
    major: "SISTEM INFORMASI - ITS",
  },
  {
    name: "GALUH MUHAMMAD G. H.",
    school: "SMA N 11 BANDUNG",
    major: "BISNIS - IPB",
  },
  { name: "UFAIRAH S. R.", school: "SMA JAGAT ARSY", major: "HUKUM - UI" },
  {
    name: "DANIEL VALENTINO M.",
    school: "SMAN 5 DENPASAR",
    major: "SBM - ITB",
  },
  {
    name: "RASAGAMA P. S.",
    school: "SMAN 2 BEKASI",
    major: "KEDOKTERAN - UNAIR",
  },
  {
    name: "CHRISTOFER W. L. K.",
    school: "SMAS DWI PUTRA",
    major: "SASTRA BELANDA - UI",
  },
  {
    name: "ATYSATYA P. A.",
    school: "SMA KHARISMA BANGSA",
    major: "GEOGRAFI - UI",
  },
  {
    name: "MUHAMMAD KEVIN A.",
    school: "SMA LABSCHOOL RAWAMANGUN",
    major: "TEKNIK INDUSTRI PERTANIAN - UB",
  },
  {
    name: "IZZAT MUHAMMAD H.",
    school: "SMAI AL- AZHAR 1",
    major: "TEKNIK MESIN - UB",
  },
  {
    name: "ELVIRA T. P.",
    school: "SMAN 9 JAKARTA",
    major: "HUKUM - UPN VETERAN JAKARTA",
  },
  {
    name: "AMODYA D. N.",
    school: "SMAN 55 JAKARTA",
    major: "KEDOKTERAN - UPN VETERAN JAKARTA",
  },
  {
    name: "AHMAD AQSHA S.",
    school: "SMA GARUDA CENDEKIA",
    major: "ILMU KOMUNIKASI - UPN VETERAN JAKARTA",
  },
  {
    name: "MUHAMMAD KUDRAT T.",
    school: "SMA PLUS N 17 PALEMBANG",
    major: "MANAJEMEN - INTER UNPAD",
  },
  {
    name: "MARSHA A. R.",
    school: "SMAN 91 JAKARTA",
    major: "SAINS DATA - UPN VETERAN JAWA TIMUR",
  },
  {
    name: "AQILA AQHNIA F. G.",
    school: "SMAN 38 JAKARTA",
    major: "FARMASI - UNAIR",
  },
  {
    name: "MUHAMMAD BINTANG F.",
    school: "SMA AL UMANAA BOARDING SCHOOL",
    major: "BAHASA DAN SASTRA INGGRIS - UNAIR",
  },
  {
    name: "NISRINA A.",
    school: "SMA DWIWARNA",
    major: "KEDOKTERAN HEWAN - UNAIR",
  },
  {
    name: "KEZYA ZEFANYA B. B.",
    school: "SMAN 3 SORONG",
    major: "STATISTIKA - UNAIR",
  },
  {
    name: "RASENDRIYA P. S.",
    school: "SMAN 2 BEKASI",
    major: "ILMU HUKUM - UNAIR",
  },
  {
    name: "KHANSA S.",
    school: "SMAN 2 PEKANBARU",
    major: "AKUNTANSI UNAIR - UNAIR",
  },
  {
    name: "SITI SAFA H.",
    school: "SMAN 1 CIANJUR",
    major: "MANAJEMEN SUMBER DAYA PERAIRAN - UNDIP",
  },
  {
    name: "RIF`AT S. B.",
    school: "SMAN 13 JAKARTA",
    major: "MANAJEMEN - UNDIP",
  },
  {
    name: "ZULFAN AROFAH A.",
    school: "MAS AL-IHSAN BALEENDAH",
    major: "KEDOKTERAN HEWAN - UNPAD",
  },
  {
    name: "TSABITUL A.",
    school: "SMAIT AL QUDWAH",
    major: "ILMU SEJARAH - UNDIP",
  },
  {
    name: "MUHAMMAD RAIHAN A. H.",
    school: "MAN 4 JAKARTA",
    major: "OSEANOGRAFI - UNDIP",
  },
  {
    name: "SITI SAFA H.",
    school: "SMAN 1 CIANJUR",
    major: "MANAJEMEN SUMBER DAYA PERAIRAN - UNDIP",
  },
  {
    name: "MARSHA AYU R.",
    school: "SMAN 91 JAKARTA",
    major: "BIOLOGI - UNIVERSITAS MULAWARMAN",
  },
  {
    name: "KHANSA S.",
    school: "SMAN 2 PEKANBARU",
    major: "AKUNTANSI DAN SEKTOR PUBLIK - UGM",
  },
  {
    name: "TSABITUL A.",
    school: "SMAIT AL QUDWAH",
    major: "SEJ. PERADABAN ISLAM DAN HUM. - UIN BANDUNG",
  },
  {
    name: "ZAKKY GHANI F. T.",
    school: "SMA IT NURUL FIKRI",
    major: "EKONOMI ISLAM UNAIR",
  },
  {
    name: "RIFQI BRANA A.",
    school: "SMAN 1 BEKASI",
    major: "DESAIN KOMUNIKASI VISUAL - UNS",
  },
  { name: "MARSHA AYU R.", school: "SMAN 91 JAKARTA", major: "GIZI - UPI" },
  {
    name: "GHAITSA T.",
    school: "SMAN 2 TANAH PUTIH",
    major: "HUKUM - UNDIP",
  },
  {
    name: "TSABITA ZAHRA R.",
    school: "SMAN 113 JAKARTA",
    major: "ILMU HUKUM - UNDIP",
  },
  {
    name: "FAUZAN RAIF D.",
    school: "SMA N 60",
    major: "BISNIS INTERNASIONAL - UNPAD",
  },
  {
    name: "PRATIWI W.",
    school: "SMA N 80 JAKARTA UTARA",
    major: "MANAJEMEN - UNJ",
  },
  {
    name: "ADINDA MUTIA R.",
    school: "SMAN 8 TANGERANG",
    major: "ILMU ADMINISTRASI BISNIS - USU",
  },
  {
    name: "MUHAMMAD HANIF M.",
    school: "SMA AL-IZHAR",
    major: "TEKNIK KIMIA - ITB INTER",
  },
  { name: "AMOS C.", school: "SMA N 20", major: "HUKUM - UNUD" },
  { name: "GASKAR A.", school: "SMAN 33 JAKARTA", major: "FARMASI - UNAIR" },
  {
    name: "MARSHA AYU R.",
    school: "SMAN 91 JAKARTA",
    major: "BIOLOGI - UNIVERSITAS HALU OLEO",
  },
  {
    name: "NASSYANDA F.",
    school: "SMAN 3 BEKASI",
    major: "D4 JURUSAN AKUNTANSI SEKTOR PUBLIK - UNPAD",
  },
  {
    name: "DIAS NANDAIKA A.",
    school: "SMAN 3 DEPOK",
    major: "KEDOKTERAN - UNJA",
  },
  {
    name: "KEZIAH P.",
    school: "SMAN 52 JAKARTA",
    major: "ADMINISTRASI PUBLIK - UNDIP",
  },
  {
    name: "SEPTIYANI L. W.",
    school: "SMAN 48 JAKARTA",
    major: "GEOFISIKA - UI",
  },
  {
    name: "PUTRI JOANNA K.",
    school: "SMAN 28 JAKARTA",
    major: "HUKUM - UGM",
  },
  {
    name: "SHAFA KAYLA A. E.",
    school: "SMAN 98 JAKARTA",
    major: "TEK. & MANAJEMEN PERIKANAN TANGKAP - IPB",
  },
  {
    name: "KHADIJA KHAIRUNNISA P. S.",
    school: "SMA ISLAM DIAN DIDAKTIKA",
    major: "ILMU HUKUM - UIN JAKARTA",
  },
  {
    name: "MUHAMMAD FADHLY D. D.",
    school: "SMA INSAN KAMIL",
    major: "TEKNIK INDUSTRI PERTANIAN - UNBRAW",
  },
  { name: "M. RIDWAN", school: "SMA 78", major: "TEKNIK MESIN - ITS" },
  {
    name: "VARIAN ADITYA P.",
    school: "SMA NEGRI 78 JAKARTA",
    major: "TEKNIK MATERIAL - ITS",
  },
  { name: "HANA RAISA Z.", school: "SMAN 6 BEKASI", major: "BIOLOGI - UNJ" },
  {
    name: "MICHAEL D. W.",
    school: "SMA BUKIT SION JAKARTA",
    major: "ILMU KOMUNIKASI - UPN VETERAN JAKARTA",
  },
  {
    name: "AISYAH L.",
    school: "SMA 8 TEBET",
    major: "PENDIDIKAN DOKTER - UI",
  },
  {
    name: "DINDA ARSILA R.",
    school: "SMAN 2 BANDUNG",
    major: "KRIMINOLOGI - UI",
  },
  {
    name: "LAURA AMANDA S.",
    school: "SMAK 7 PENABUR",
    major: "PENDIDIKAN DOKTER - UI",
  },
  {
    name: "KEISHA SOFIANADA P.",
    school: "SMAN 36 JAKARTA",
    major: "ILMU KOMUNIKASI - UNESA",
  },
  {
    name: "NADJA ADAIRA P.",
    school: "SMAN 78 JAKARTA",
    major: "TEKNIK INDUSTRI - ITS",
  },
  {
    name: "WIBISANA W.",
    school: "SMA N 5 BEKASI",
    major: "TEKNOLOGI INDUSTRI - ITB",
  },
  {
    name: "RAUL FRANCIS W. S.",
    school: "SMAT KRIDA NUSANTARA",
    major: "ILMU HUKUM - UDAYANA",
  },
  {
    name: "DEWITA A.",
    school: "SMA 3",
    major: "ADMINISTRASI ASURANSI DAN AKTUARIA - D3 UI",
  },
  {
    name: "NAZLA AMANDA A. S.",
    school: "SMAN 98 JAKARTA",
    major: "AGRIBISNIS - UIN JAKARTA",
  },
  {
    name: "ANDI ZAHIRAH A.",
    school: "SMA 104 JAKARTA",
    major: "KEDOKTERAN - UPN VETERAN JAKARTA",
  },
  {
    name: "AZAHRA KAULIKA I.",
    school: "SMAN 113 JAKARTA",
    major: "JURNALISTIK - UIN JAKARTA",
  },
  {
    name: "HANA RAISA Z.",
    school: "SMAN 6 BEKASI",
    major: "FISIOTERAPI - UI D4",
  },
  { name: "NAUFAL A.", school: "CITA BUANA", major: "MANAJEMEN - UI INTER" },
  {
    name: "AMELIA AYU S.",
    school: "SMA TARUNA NUSANTARA",
    major: "TEKNIK INDUSTRI - UI",
  },
  {
    name: "RIFQY AUDZAN R.",
    school: "SMA AL AZHAR 1",
    major: "TEKNIK ELEKTRO - UI",
  },
  {
    name: "MUHAMAD RAIHAN I.",
    school: "SMAIT TUNAS BANGSA DEPOK",
    major: "VOKASI PENYIARAN MULTIMEDIA - UI",
  },
  {
    name: "DEWITA A.",
    school: "SMA 3",
    major: "EKONOMI SYARIAH - UPN VETERAN JAKARTA",
  },
  {
    name: "DANIEL A. Z",
    school: "SMA N 10",
    major: "EKONOMI PEMBANGUNAN - UNS",
  },
  {
    name: "CLARICE C. W.",
    school: "SMAN 6 BOGOR",
    major: "TEKNIK KIMIA - UI",
  },
  {
    name: "ANGGININDA S. D. S.",
    school: "SMAN 60 JAKARTA",
    major: "FARMASI - UNAIR",
  },
  {
    name: "MAHOGRA S. A.",
    school: "SMA PRESIDEN",
    major: "TEKNOLOGI DAN MANAJEMEN PERIKANAN TANGKAP - IPB",
  },
  {
    name: "MUTHIA H.",
    school: "MAN 1 KOTA BEKASI",
    major: "INFORMATIKA - UPN VETERAN JAKARTA",
  },
  {
    name: "FARICA T.",
    school: "SMA SANTA ANGELA BANDUNG",
    major: "HUBUNGAN MASYARAKAT - UNPAD",
  },
  {
    name: "AMARADEA M.",
    school: "SMA AL-IZHAR JAKARTA",
    major: "ARSITEKTUR KELAS INTERNASIONAL - UI",
  },
  {
    name: "BERNADINE ANASTASYA R.",
    school: "BINUS INTERNASIONAL SCHOOL SIMPRUG",
    major: "FK KELAS INTERNASIONAL - UI",
  },
  {
    name: "GARUDA MUHAMMAD E.",
    school: "SMA PRESIDEN",
    major: "TEKNIK INDUSTRI KELAS INTERNASIONAL - UI",
  },
  {
    name: "CHIARA D.C.",
    school: "SMA DWIWARNA",
    major: "ARSITEKTUR KELAS INTERNASIONAL - ITS",
  },
  {
    name: "NADIA A.",
    school: "S1 UNIVERSITAS TRISAKTI",
    major: "ADMINISTRASI RUMAH SAKIT - S2 UI",
  },
  {
    name: "HARITS SURYA F.",
    school: "OLIFANT HIGH SCHOOL",
    major: "ILMU KOMPUTER INTER - UGM",
  },
  {
    name: "GIBRAN R. S.",
    school: "BINUS SCHOOL BEKASI",
    major: "HUBUNGAN INTERNASIONAL - UGM",
  },
  {
    name: "REYNARD R. B.",
    school: "SMA INSAN CENDEKIA MADANI",
    major: "TEKNIK INFORMATIKA - UB",
  },
  {
    name: "SELLINA M. A.",
    school: "SMA BUDI LUHUR",
    major: "ILMU ADMINISTRASI NEGARA - UI",
  },
  {
    name: "NADILA NUR S.",
    school: "SMAI NURUL FIKRI SERANG",
    major: "PENDIDIKAN DOKTER GIGI - UNSRI",
  },
  {
    name: "ZEASHAFA Z. R.",
    school: "SMAN 97 JAKARTA",
    major: "FARMASI - UPN VETERAN JAKARTA",
  },
  {
    name: "MUHAMMAD KAREEM M. N.",
    school: "SMAN 37 JAKARTA SELATAN",
    major: "HUKUM - UPN VETERAN JAKARTA",
  },
  {
    name: "FARROS F. A.",
    school: "SMK RADEN UMAR SAID KUDUS JAWA TENGAH",
    major: "FSRD - ITB",
  },
  { name: "AKBAR R.", school: "SMA ALBAYAN", major: "TEKNIK MESIN - UI" },
  {
    name: "NASHIFA N. K.",
    school: "SMA N 1 CIBADAK",
    major: "PENDIDIKAN DOKTER - UNPAD",
  },
  {
    name: "OEMMIZAHY D. P.",
    school: "MAN 1 KOTA BEKASI",
    major: "PENDIDIKAN TATA BUSANA - UPI",
  },
  {
    name: "AMALIYAH KANYA S.",
    school: "SMAIT AL-KAHFI",
    major: "PSIKOLOGI - UNJ",
  },
  {
    name: "MUHAMMAD PRAJA D.",
    school: "SMK IDN BOARDING SCHOOL",
    major: "PENDIDIKAN INFORMATIKA - UNJ",
  },
  { name: "MUHAMMAD RAFLI S.", school: "SMA N 99", major: "ARSITEKTUR - UB" },
  {
    name: "AHMAD RO'IN F.",
    school: "SMAN 8 BOGOR",
    major: "FARMASI - UPN VETERAN JAKARTA",
  },
  {
    name: "MOZA R. I.",
    school: "SMAN 5 BALIKPAPAN",
    major: "INFORMATIKA - UPN VETERAN JAKARTA",
  },
  {
    name: "NAUFAL F. W.",
    school: "SMA UNGGUL AL BAYAN",
    major: "REKAYASA NANOTEKNOLOGI - UNAIR",
  },
  {
    name: "ALIFIA C. N.",
    school: "SMAN 34 JAKARTA",
    major: "SASTRA CINA - UI",
  },
  {
    name: "DEWA AYU P. M.",
    school: "SMAN 4 DENPASAR",
    major: "KEDOKTERAN - UNUD",
  },
  {
    name: "VISANTI S.",
    school: "SMAN 28 JAKARTA",
    major: "AGROTEKNOLOGI - UNPAD",
  },
  { name: "CHIARA D. C.", school: "SMA DWIWARNA", major: "SAPPK - ITB" },
  { name: "GIOVANNI P. T.", school: "SMAN 91", major: "AKUAKULTUR - UNSOED" },
  {
    name: "NISA BELLA M. N.",
    school: "SMAI AL AZHAR 19",
    major: "KESEHATAN MASYAKARAT - UPN VETERAN JAKARTA",
  },
  {
    name: "CORDOVA M. W.",
    school: "SMAN 68 JAKARTA",
    major: "TEKNIK INDUSTRI - UI",
  },
  {
    name: "ACHMAD SHAFWAN Z.",
    school: "SMAN 34 JAKARTA",
    major: "STEI-R ITB",
  },
  {
    name: "RAFFI ARSYA P.",
    school: "PONDOK PESANTREN DARUNNAJAH",
    major: "PERPAJAKAN - UB",
  },
  {
    name: "KEZIA CRYSTABELLA M. H.",
    school: "SMAN 81 JAKARTA",
    major: "HUKUM - UGM",
  },
  {
    name: "FARREL SHEVA A.",
    school: "SMAN 6 JAKARTA",
    major: "ILMU KOMPUTER - UI",
  },
  {
    name: "YUSRI A. F.",
    school: "SMAN 3 SAMARINDA",
    major: "STATISTIKA - UNMUL",
  },
  {
    name: "MANIKA C. L.",
    school: "SMA AL AZHAR 8 BEKASI",
    major: "TEKNOLOGI PANGAN - UNDIP",
  },
  {
    name: "RAFI AHMAD S.",
    school: "SMA MADANIA",
    major: "TEKNIK INDUSTRI - UB",
  },
  {
    name: "MILKA F.",
    school: "SMAK PENABUR BINTARO JAYA",
    major: "FSRD - ITB",
  },
  {
    name: "RAKA PRATAMA S.",
    school: "MA HUSNUL KHOTIMAH",
    major: "ILMU KELAUTAN - UNDIP",
  },
  {
    name: "AQILURRACHMAN A. C.",
    school: "PKBM KAK SETO",
    major: "ANTROPOLOGI BUDAYA - UGM",
  },
  {
    name: "NISA BELLA M. N.",
    school: "SMAI AL AZHAR 19",
    major: "TEKNIK INDUSTRI PERTANIAN - UB",
  },
  {
    name: "BINTANG PUTERA A.",
    school: "SMA TARUNA NUSANTARA",
    major: "TEKNIK MESIN - UNDIP",
  },
  {
    name: "MAHESA S.",
    school: "PKBM WINDSOR BEKASI",
    major: "FILSAFAT - UGM",
  },
  {
    name: "CARMELO O. W.",
    school: "SMA 55 JAKARTA",
    major: "PSIKOLOGI INTERNASIONAL - UI",
  },
  {
    name: "KHAILA ATIKAH P. S.",
    school: "SMAN 91 JAKARTA",
    major: "PSIKOLOGI - UNDIP",
  },
  {
    name: "MUHAMAD RAKHA A.",
    school: "SMAI AL-AZHAR 19 CIRACAS",
    major: "ILMU ADMINISTRASI NEGARA - UI",
  },
  {
    name: "DAMAR ADI W.",
    school: "SEKOLAH CITA BUANA",
    major: "MANAJEMEN INTERNASIONAL - UI",
  },
  {
    name: "KHAILA ATIKAH P. S.",
    school: "SMAN 91 JAKARTA",
    major: "ILMU KOMUNIKASI - UPN VETERAN JAKARTA",
  },
  {
    name: "NISA BELLA M. N.",
    school: "SMAI AL AZHAR 19",
    major: "TEKNIK LINGKUNGAN - UI",
  },
  {
    name: "TABINA A.",
    school: "HIGHSCOPE INDONESIA",
    major: "ILMU KOMUNIKASI INTERNASIONAL - UI",
  },
  {
    name: "MUHAMMAD TOHIR E. H.",
    school: "SMAN 37 JAKARTA",
    major: "TEKNIK INDUSTRI - UI",
  },
  {
    name: "NAURAH K. D. Z.",
    school: "SMA IIHS",
    major: "KEDOKTERAN - UPN VETERAN JAKARTA",
  },
  {
    name: "NUHASHIFA R. K.",
    school: "AL-WILDAN INTERNATIONAL ISLAMIC SCHOOL",
    major: "KEPERAWATAN INTERNASIONAL - UNSOED",
  },
  {
    name: "KESIA SANTANA L.",
    school: "BINUS SCHOOL SIMPRUG",
    major: "MANAJEMEN INTERNASIONAL - UI",
  },
  {
    name: "THUFAIL R.",
    school: "SMA LABSCHOOL JAKARTA",
    major: "TEKNIK ELEKTRO - UI",
  },
  {
    name: "UFAIRAH S. R.",
    school: "SMA JAGAT ARSY",
    major: "ILMU KOMUNIKASI - UI",
  },
  {
    name: "NISA BELLA M. N.",
    school: "SMAI AL AZHAR 19",
    major: "SUPERVISOR JAMINAN MUTU PANGAN - D3 IPB",
  },
  {
    name: "RICKY S.",
    school: "SMA N 1 PURWOKERTO",
    major: "SISTEM INFORMASI - UI",
  },
  {
    name: "ALYA ANDITA D.",
    school: "SMA KOLESE LOYOLA",
    major: "FARMASI - UGM",
  },
  {
    name: "SHOFWAH A. N.",
    school: "JAKARTA ISLAMIC SCHOOL",
    major: "ILMU EKONOMI - UI",
  },
  {
    name: "KELVIN KENZIE M.",
    school: "SMAS PRIBADI BEJI",
    major: "TEKNIK INFANSTRUKTUR LINGKUNGAN - UGM",
  },
  {
    name: "NUHASHIFA R. K.",
    school: "AL-WILDAN INTERNATIONAL ISLAMIC SCHOOL",
    major: "KIMIA - ITS",
  },
  {
    name: "DINDA D. N.",
    school: "SMA PLUS PGRI CIBINONG",
    major: "HUMAS - UPN VETERAN YOGYAKARTA",
  },
  {
    name: "NAURAH K. D. Z.",
    school: "SMA IIHS",
    major: "PERENCANAAN WILAYAH DAN KOTA - UNDIP",
  },
  {
    name: "FEBRIANA A. P.",
    school: "SMAN 1 TANGERANG SELATAN",
    major: "HUKUM - UDAYANA",
  },
  {
    name: "MIFTAHUL J.",
    school: "SMAN 5 KOTA BENGKULU",
    major: "PENDIDIKAN DOKTER - UNPAD",
  },
  {
    name: "GIOVANNI P. T.",
    school: "SMAN 91 JAKARTA",
    major: "KESELAMATAN DAN KESEHATAN KERJA - UI",
  },
  {
    name: "BINTANG PUTERA A.",
    school: "SMA TARUNA NUSANTARA",
    major: "TEKNIK GEOLOGI - UNPAD",
  },
  {
    name: "RAKA PRATAMA S.",
    school: "MA HUSNUL KHOTIMAH",
    major: "PERIKANAN K. PANGANDARAN - UNPAD",
  },
  {
    name: "M. KHADAFFI H. S.",
    school: "MA SUNAN PANDANARAN",
    major: "MANAJEMEN KOMUNIKASI - UNPAD",
  },
  {
    name: "DAVINA RIZKIKA T.",
    school: "SMA SULTHON AULIA BOARDING SCHOOL",
    major: "PSIKOLOGI - UNPAD",
  },
  {
    name: "NUHASHIFA R. K.",
    school: "AL-WILDAN INTERNATIONAL ISLAMIC SCHOOL",
    major: "FISIOTERAPI - UNHAS",
  },
  {
    name: "NISA BELLA M. N.",
    school: "SMAI AL AZHAR 19",
    major: "TEKNOLOGI INDUSTRI PERTANIAN - UNPAD",
  },
  {
    name: "KELVIN KENZIE M.",
    school: "SMAS PRIBADI BEJI",
    major: "TEKNIK LINGKUNGAN - UB",
  },
  {
    name: "RANIA AZIZA S.",
    school: "AL IZHAR PONDOK LABU",
    major: "ILMU HUKUM - UI",
  },
  {
    name: "ATHIRA TIARA P.",
    school: "SMA LABSCHOOL RAWAMANGUN",
    major: "SASTRA JERMAN - UI",
  },
  {
    name: "ZIVA MUHAMMAD N.",
    school: "MA HUSNUL KHOTIMAH",
    major: "TEKNIK SIPIL - UNDIP",
  },
  {
    name: "DINDA D. N.",
    school: "SMA PLUS PGRI CIBINONG",
    major: "SOSIOLOGI - UNS",
  },
  {
    name: "DELFIN AHMAD A.",
    school: "AL JABR ISLAMIC SCHOOL",
    major: "ENTREPRENEURSHIP - ITB",
  },
  {
    name: "KAYLA TABINA A.",
    school: "SEKOLAH CITA BUANA",
    major: "MANAGEMENT - ITB",
  },
  {
    name: "MATTHEW RISDIAN P. S.",
    school: "SMA N 11 DEPOK",
    major: "KEDOKTERAN - UNAIR",
  },
  { name: "AHMAD JULIO U.", school: "SMA YAPNI", major: "MANAJEMEN - UNRAM" },
];
